/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IEpochControllerInterface extends ethers.utils.Interface {
  functions: {
    "epoch()": FunctionFragment;
    "nextEpochAllocatedReward(address)": FunctionFragment;
    "nextEpochLength()": FunctionFragment;
    "nextEpochPoint()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "epoch", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextEpochAllocatedReward",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEpochLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextEpochPoint",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "epoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextEpochAllocatedReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEpochLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEpochPoint",
    data: BytesLike
  ): Result;

  events: {};
}

export class IEpochController extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IEpochControllerInterface;

  functions: {
    epoch(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "epoch()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    nextEpochAllocatedReward(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "nextEpochAllocatedReward(address)"(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    nextEpochLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "nextEpochLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    nextEpochPoint(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "nextEpochPoint()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  epoch(overrides?: CallOverrides): Promise<BigNumber>;

  "epoch()"(overrides?: CallOverrides): Promise<BigNumber>;

  nextEpochAllocatedReward(
    _pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "nextEpochAllocatedReward(address)"(
    _pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  nextEpochLength(overrides?: CallOverrides): Promise<BigNumber>;

  "nextEpochLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

  "nextEpochPoint()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    "epoch()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochAllocatedReward(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "nextEpochAllocatedReward(address)"(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextEpochLength(overrides?: CallOverrides): Promise<BigNumber>;

    "nextEpochLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

    "nextEpochPoint()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    "epoch()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochAllocatedReward(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "nextEpochAllocatedReward(address)"(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextEpochLength(overrides?: CallOverrides): Promise<BigNumber>;

    "nextEpochLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

    "nextEpochPoint()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    epoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "epoch()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nextEpochAllocatedReward(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nextEpochAllocatedReward(address)"(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextEpochLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nextEpochLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextEpochPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nextEpochPoint()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
